services:
  auth.identityprovider:
    image: ${DOCKER_REGISTRY-}identityproviderapi
    build:
      context: .
      dockerfile: Auth.IdentityProvider/Dockerfile
    ports:
      - "7255:8080"
      - "5012:8081"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"

  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: Keycloak
    command:
      - start-dev
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
    ports:
      - "18080:8080"
      
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: Jaeger
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"
